#!/bin/bash
#
#script to checkin files in rcs

make
if [ "$?" != "0" ]
then
	echo "make failed"
	exit 1
else
	echo "make completed,hit return"
fi

read v
sudo insmod ./modules/lkm.ko num_dev=16
dmesg
read v

cat /proc/devices
read v

sudo mknod /dev/scratch_node c 251 0
read v
ls -la /dev/s*
read v

gcc application.c -o application

sudo ./application /dev/scratch_node
read v

sudo rmmod lkm
dmesg
read v

cat /proc/devices
read v

sudo unlink /dev/scratch_node

rm -rf modules
rm -f modules.order
rm -f Module.symvers
