#!/bin/bash
#
make
if [ "$?" != "0" ]
then
	echo "make failed"
	exit 1
else
	echo "make completed,hit return"
fi

read v
sudo insmod ./modules/lkm.ko num_dev=1
dmesg
read v

cat /proc/devices
read v

sudo mknod /dev/scratch_node c 251 0
read v
ls -la /dev/sc*
read v

gcc -o app_writer app_writer.c
if [ "$?" != "0" ]
then
	echo "app_writer compilation failed"
	exit 1
else
	echo "app_writer compilation succeeded"
fi

sudo ./app_writer dev/scratch_node
read v

echo "run script reader and writer in different"
echo "computer or hit return to remove module"
read v

read v
sudo rmmod lkm
dmesg
read v

cat /proc/devices
read v

sudo unlink /dev/scratch_node
echo "Module operations successful!!"
