#!/bin/bash
#
#script to checkout files from rcs for editing

co -l header.h
co -l declarations.h
co -l init.c
co -l cleanup.c
co -l open_dev.c
co -l close_dev.c
co -l write_dev.c
co -l create_scull.c
co -l read_dev.c
co -l app_reader.c
co -l app_writer.c
