#!/bin/bash
#
#script to test module

make
if [ "$?" != "0" ]
then
	echo "make failed"
	exit 1
else
	echo "make completed,hit return"
fi

read v
sudo insmod ./modules/lkm.ko num_dev=16
dmesg
read v

cat /proc/devices
read v

sudo mknod /dev/scratch_node c 251 0
read v
ls -la /dev/sc*
read v

gcc -o application application.c
if [ "$?" != "0" ]
then
	echo "application compilation failed"
	exit 1
else
	echo "application compilation succeeded,hit return"
fi

gcc -o application2 application2.c
if [ "$?" != "0" ]
then
	echo "application2 compilation failed"
	exit 1
else
	echo "application2 compilation succeeded,hit return"
fi

sudo ./application /dev/scratch_node > app_log
#sudo ./application2 /dev/scratch_node > app2_log
read v

echo "hit return to remove module"
read v
sudo rmmod lkm
dmesg
read v

cat /proc/devices
read v

sudo unlink /dev/scratch_node
echo "Module operations successful!!"
make clean
echo "file cleanup done."
