#!/bin/bash
#
#script to test module 

make
if [ "$?" != "0" ]
then
	echo "make failed"
	exit 1
else
	echo "make completed,hit return"
fi

read v
sudo insmod ./modules/lkm.ko num_dev=16
dmesg
read v

cat /proc/devices
read v

sudo mknod /dev/scratch_node c 251 0
read v
ls -la /dev/sc*
read v

gcc -o app1 app1.c
if [ "$?" != "0" ]
then
	echo "app1 compilation failed"
	exit 1
else
	echo "app1 compilation succeeded,hit return"
fi

gcc -o app2 app2.c
if [ "$?" != "0" ]
then
	echo "app2 compilation failed"
	exit 1
else
	echo "app2 compilation succeeded,hit return"
fi

sudo ./app1 /dev/scratch_node > app1_log &
sudo ./app2 /dev/scratch_node > app2_log
read v

echo "hit return to remove module"
read v
sudo rmmod lkm
dmesg
read v

cat /proc/devices
read v

sudo unlink /dev/scratch_node
echo "Module operations successful!!"
make clean
echo "file cleanup done."
